# Generated by Django 4.0.4 on 2022-04-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikename', models.CharField(max_length=30)),
                ('bikecode', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('image1', models.ImageField(upload_to='files/covers')),
                ('image2', models.ImageField(upload_to='files/covers')),
                ('image3', models.ImageField(upload_to='files/covers')),
            ],
        ),
    ]
