# Generated by Django 4.0.4 on 2022-04-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_manufacture', models.DateField()),
                ('bike_color', models.CharField(max_length=30)),
                ('bike_engine', models.CharField(max_length=128)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('integrated_technology', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('bikecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bike')),
            ],
        ),
    ]
